### ISSUE TITLE
Add support for arm* architectures

### ISSUE THREAD

**Issue by anadahz** [ooni/probe-cli#28] opened 2019-04-24 13:57 UTC
Having support for multiple arm* architectures is crucial in order to run the probe on embedded devices. 
Below a list of the bare minimum necessary architectures for different versions of Raspberry Pi (a mainstream embedded device), compatible with other embedded devices such as the Orange Pi:
- [ ] armel
- [ ] armhf
- [ ] arm64

**Comment by hellais** [comment] 2019-04-24 13:59
This is a duplicate of: https://github.com/ooni/probe/issues/807

**Closed** 2019-04-24 13:59 UTC
Labels: duplicate

**Comment by anadahz** [comment] 2019-04-24 14:08
@hellais is https://github.com/ooni/probe/issues/ the cannonical place to open tickets for probe-cli?
Perhaps this should be mentioned in README.

**Comment by hellais** [comment] 2019-04-24 14:14
Technically speaking this could have been filed here as well. probe is the issue tracker for things that are possibly affect all distribution (mobile, desktop, cli, etc.), while probe-cli is just for the Command Line Interface client.

I marked it as duplicate as that issues had been opened prior to this and it has a bunch more information in it that can help you get started on working on it :)

**Comment by nunesgh** [comment] 2020-10-02 19:14
According to ooni/probe#807 it is already possible to build on Raspberry Pi. But would it also be possible to add the linux_arm* files to the [official release](https://github.com/ooni/probe-cli/releases), as is already done for linux_amd64?
