### ISSUE TITLE
Add support for log options config

### ISSUE THREAD

**Issue by anadahz** [ooni/probe-cli#24] opened 2018-12-11 19:44 UTC
It will be very useful to have support for a variety of log options that can be tweaked in the config file such as:
- loglevel
- log_path
- log_rotation options

**Comment by hellais** [comment] 2018-12-12 10:48
This is a good wishlist item, yet we need to see how and if it's possible to do this in light of the fact that the data from probe-cli needs to be consumed by probe-desktop.

Log rotation is probably something we do not want to implement inside of probe-cli, as you are in most cases better of doing your rotation with the OS provided method.

Keep in mind that the development of probe-cli is very closely related to probe-desktop, so these sorts of changes are generally informed based on the needs of the desktop app.

**Comment by bassosimone** [comment] 2019-05-23 14:19
I don't think there's a daemon here. Maybe it will be possible to compose some daemon like behaviour by combining probe-cli and systemd, but then there's no need for us to implement it.

**Comment by hellais** [comment] 2019-05-23 16:28
Yeah probe-cli does not behave as a daemon and that is by design. By not having a long running process we avoid several issues we had with ooniprobe-agent.

I don't think there is anything that we used to be able to do in the past that cannot be done with a periodic execution on a user configured schedule (using cron or systemd) compared to probe-legacy.

If there are missing features they should be documented explicitly

**Comment by bassosimone** [comment] 2019-05-23 16:40
Right, so this sounds like something we won't fix.

**Closed** 2019-05-25 08:43 UTC
Labels: enhancement, question, wontfix
